<?php

namespace Jp7\InterAdmin\Field;

use Illuminate\Support\Str;

class Factory
{
    protected $namespace = 'Jp7\\InterAdmin\\Field\\';
    /*
    protected $map = [
        'text' => [],
        'varchar' => [],
        'char' => [],
        'file' => [],
        'date' => [],
        'select' => [],
        'select_multi' => [],
        'special' => [],
        'tit' => [],
        'func' => []
    ];
    */
    /**
     * @param array[] $campos As generated by Type->getFields()
     * @return FieldInterface[]
     */
    public function makeFromFields(array $campos): array
    {
        return array_map([$this, 'makeField'], $campos);
    }

    /**
     * @param array $field As generated by Type->getFields()
     * @return FieldInterface
     */
    public function makeField(array $field)
    {
        // tipo_de_campo -> only used in a few specials / xtra_disabledfields
        $tipo = empty($field['field_type']) ? $field['type'] : $field['field_type'].'_';
        $prefix = $this->getPrefix($tipo, $field['xtra'] ?? '');

        // A field class is namespaced and holds no `::`. `Ci\Field\Produtos` is one;
        // `InterAdmin\CustomField::field` is a callable carrying the same backslash, and
        // instantiating it is "Class not found" on the record form and the list.
        if (($prefix === 'special' || $prefix === 'func')
            && str_contains($field['name'], '\\')
            && !str_contains($field['name'], '::')) {
            // Special as object implements FieldInterface
            // Special as callable should be deprecated in favor of object
            $class = $field['name'];
            $field['name'] = $field['nome_original'] ?? $field['name'];
        } else {
            $class = $this->namespace . Str::studly($prefix).'Field';
        }

        return new $class($field);
    }

    protected function getPrefix($tipo, $xtra): string
    {
        $prefix = explode('_', $tipo)[0];
        if ($prefix === 'select') {
            if (Str::startsWith($tipo, 'select_multi_')) {
                $prefix .= '_multi'; // SelectMultiField
                if (in_array($xtra, [SelectMultiField::XTRA_RECORD_SEARCH, SelectMultiField::XTRA_TYPE_SEARCH])) {
                    $prefix .= '_ajax'; // SelectMultiAjaxField
                }
            } else {
                if (in_array($xtra, [SelectField::XTRA_RECORD_AJAX, SelectField::XTRA_TYPE_AJAX])) {
                    $prefix .= '_ajax'; // SelectAjaxField
                } elseif (in_array($xtra, [SelectField::XTRA_RECORD_RADIO, SelectField::XTRA_TYPE_RADIO])) {
                    $prefix .= '_radio'; // SelectRadioField
                }
            }
        }
        return $prefix;
    }
}
