<?php

namespace Jp7\Interadmin\Field;

use Illuminate\Support\Str;

class Factory
{
    protected $namespace = 'Jp7\\Interadmin\\Field\\';
    /*
    protected $map = [
        'text' => [],
        'varchar' => [],
        'char' => [],
        'file' => [],
        'date' => [],
        'select' => [],
        'select_multi' => [],
        'special' => [],
        'tit' => [],
        'func' => []
    ];
    */
    /**
     * @param array[] $campos As generated by Type->getFields()
     * @return Jp7_Interadmin_Field_Base[]
     */
    public function makeFromCampos(array $campos)
    {
        return array_map([$this, 'makeField'], $campos);
    }

    /**
     * @param array $campo As generated by Type->getFields()
     * @return Jp7_Interadmin_Field_Base
     */
    public function makeField(array $campo)
    {
        // tipo_de_campo -> only used in a few specials / xtra_disabledfields
        $type = empty($campo['tipo_de_campo']) ? $campo['tipo'] : $campo['tipo_de_campo'].'_';
        $prefix = $this->getPrefix($type, $campo['xtra'] ?? '');

        if (($prefix === 'special' || $prefix === 'func') && str_contains($campo['nome'], '\\')) {
            // Special as object implements FieldInterface
            // Special as callable should be deprecated in favor of object
            $class = $campo['nome'];
            $campo['nome'] = $campo['nome_original'] ?? $campo['nome'];
        } else {
            $class = $this->namespace . Str::studly($prefix).'Field';
        }

        return new $class($campo);
    }

    /**
     * @param string
     */
    protected function getPrefix($type, $xtra)
    {
        $prefix = explode('_', $type)[0];
        if ($prefix === 'select') {
            if (Str::startsWith($type, 'select_multi_')) {
                $prefix .= '_multi'; // SelectMultiField
                if (in_array($xtra, [SelectMultiField::XTRA_RECORD_SEARCH, SelectMultiField::XTRA_TYPE_SEARCH])) {
                    $prefix .= '_ajax'; // SelectMultiAjaxField
                }
            } else {
                if (in_array($xtra, [SelectField::XTRA_RECORD_AJAX, SelectField::XTRA_TYPE_AJAX])) {
                    $prefix .= '_ajax'; // SelectAjaxField
                } elseif (in_array($xtra, [SelectField::XTRA_RECORD_RADIO, SelectField::XTRA_TYPE_RADIO])) {
                    $prefix .= '_radio'; // SelectRadioField
                }
            }
        }
        return $prefix;
    }
}
